#spring mail  
mail:
 smtp:
  username: 1134926238@qq.com
  password: 123434321
  smtpServer: smtp.qq.com
  port: 465
  fromMailAddress: 1134926238@qq.com
  auth: true
  timeout: 1000

#时间戳统一转换
spring.jackson.time-zone : GMT+8
spring.jackson.date-format: yyyy-MM-dd HH:mm:ss
spring.jackson.joda-date-time-format: yyyy-MM-dd HH:mm:ss

# Server port
server:
  port: 60011
  contextPath: /service_rc

# 跨域访问
cors.allow.origin: '*'

#是否记录日志到数据库
isLog:
  write: true
  read: false

#MyBatis配置文件地址
mybatis:
  configLocation: mybatis-config.xml
  
# 打印sql  
logging:  
 level: 
   com.run.dao.unity: DEBUG

# MySQL config
spring:
  datasource:
    #本地环境
    url: jdbc:mysql://59.110.142.82:3306/service_rc?characterEncoding=utf8&useSSL=false&autoReconnect=true&failOverReadOnly=false&autoReconnectForPools=true
    username: root
    password: 19971104
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 80     #最大活动连接
    initialSize: 10   #初始化连接
    maxIdle: 60       #最大空闲连接
    minIdle: 10       #最小空闲连接
    maxWait: 3000     #从池中取连接的最大等待时间，单位ms
    validationQuery: SELECT 1  #验证使用的SQL语句
    testWhileIdle: true      #指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除.
    testOnBorrow: false      #拿出连接时不要测试，否则很影响性能
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    timeBetweenEvictionRunsMillis: 30000  #每30秒运行一次空闲连接回收器
    minEvictableIdleTimeMillis: 1800000   #池中的连接空闲30分钟后被回收
    numTestsPerEvictionRun: 3 #在每次空闲连接回收器线程(如果有)运行时检查的连接数量

  thymeleaf.cache: false
  freemarker.cache: false
  velocity.cache: false
  groovy.template.cache: false
   
  mvc:
    favicon:
      enabled: false
      


  multipart:  
    enabled: true  
    max-file-size: 1000mb  
    max-request-size: 1000mb
    
# mongoProperties
service_rc:
#测试环境
  address : 192.168.200.39
  port : 27017
  maxConnect : 50
  maxWaitThread : 100
  maxTimeOut : 300
  maxWaitTime : 300
  database : service_rc
  collection : DaIotMonitorData

    
#文件上传
upload:
#本地环境
   diskPath : D:\ProgramData\ApplicationResource\
   linkPath : http://localhost/resource
   swfPath : http://192.168.200.193:8081/resource/swf/flvplayer.swf
#定时任务开关
mangoTaskSwitch:
  sentimentTask : false
  ecTask : false
  wholesaleTask : false

